name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.117.0'
          extended: false

      - name: Merge config files
        run: |
          cp config/_dafault/config.yaml config/merged.yaml
          cat config/_dafault/languages.yaml >> config/merged.yaml
          cat config/_dafault/menus.yaml >> config/merged.yaml
          cat config/_dafault/params.yaml >> config/merged.yaml

      - name: Build
        run: hugo --config config/merged.yaml --minify


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./public
